

# 服务器配置
server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 256
  servlet:
    session:
      tracking-modes: cookie


# 项目全局配置
project:
  # 项目名称
  name: newbee-mall-plus
  # 上传文件的默认url前缀，根据部署设置自行修改，windows下路径
  fileUploadPath: D:\\upload\\
  # 订单未支付超期时间，单位秒
  orderUnpaidOverTime: 300
  # 服务器地址
  serverUrl: http://localhost:8080

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /admin/*,

# spring配置
spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  session:
    timeout: 3600S
    redis:
      namespace: newbee-mall-plus:session


# mybatis配置
mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id:
  rsa-private-key:
  alipay-public_key:
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  log-path: D://newbee-mall-plus//log
  signtype: RSA2
